### ISSUE TITLE
An unexpected error occurred in alias: Error: Expected scaling rules for DCs (400)

### ISSUE THREAD

**Issue by mrmartineau** [vercel/vercel#1296]
```
now -v
11.1.4
```

After running `now alias` (having previously run `now` to deploy the latest version of my code), I receive this error:

```
> Assigning alias pinboard-api.now.sh to deployment pinboard-api-oubedhggbm.now.sh
> Error! An unexpected error occurred in alias: Error: Expected scaling rules for DCs (400)
    at responseError (/snapshot/repo/dist/now.js:1632:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I have tried redploying, updated dependencies but because the deployment has already taken place, the `now alias` call should just do the switch on an already deployed instance.

What to do?

**Comment by mrmartineau** [comment]
FYI, creating a new alias with the same deployment works as expected. 
```
now alias pinboard-api-uyxgzttyic.now.sh pinboard-api2.now.sh
```
..so I thought that removing and adding the old alias might fix the problem.. and what do you know? It did!

```sh
now alias rm pinboard-api.now.sh
now alias pinboard-api-uyxgzttyic.now.sh pinboard-api.now.sh
```

**Comment by alxpez** [comment]
I have the same issue, and while deleting the alias and re-setting it to the new deploy works, it is not really a solution. In the past versions the alias would just be switching deployments w/o a problem.

This looks like an actual issue, or a breaking change.

EDIT: using version `11.1.7`

**Comment by sean-nicholas** [comment]
Have the same issue on `11.1.12` Should this issue be reopened?

**Comment by brunogarcia** [comment]
The same problem with `11.1.14` version

**Comment by mrmartineau** [comment]
@leo @rauchg can you say if this bug will be fixed? If not, how someone could submit a fix.

**Comment by javivelasco** [comment]
Will investigate this. Of course any PR is always appreciated!

**Comment by sean-nicholas** [comment]
Worked fine yesterday with version 11.2.4

**Comment by nicnocquee** [comment]
Still happening in `11.2.9`

**Comment by eAi** [comment]
I'm getting this error in 11.3.0. It occurred after I got an error saying that I had too many instances (I had one), which I 'fixed' by setting the scale to 0. This then happened next time I tried to alias.

**Comment by franky47** [comment]
Same here in `11.4.6`. I `now scale`'d all the instances of a project (which had an alias) to 0 to allow another deployment, then tried to alias that new deployment, but had the error both through the now.json `alias` setting and through the full CLI `alias` command.
Deleting the alias and re-creating solved the problem.

**Comment by simonkubica** [comment]
Same error on my end.

>Assigning alias ---.com.au to deployment ---.now.sh
Error! An unexpected error occurred in alias: Error: Response Error (500)
at responseError (/snapshot/repo/dist/now.js:2700:15)
at module.exports.EventEmitter.fetch.opts.retry (/snapshot/repo/dist/now.js:2402:27)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)`

`now -v 11.4.6`

**Update:** Fixed by redeploying with `now` and then creating an alias again with the new url.

**Comment by ghost** [comment]
Seems like it’s still an issue. Haven’t experienced it before. Here is the output:

    > Error! An unexpected error occurred in alias: Error: Response Error (500)
        at responseError (/snapshot/repo/dist/now.js:2709:15)
        at module.exports.fetch.retry (/snapshot/repo/dist/now.js:2439:27)
        at process._tickCallback (internal/process/next_tick.js:68:7)

I was still on version 1. Then I upgraded by setting `"version"` to `2` in `now.json` and upgrading `now` using `npm i -g`. That didn’t solve the problem. I also tried to delete the alias, but that didn’t help.

Edit: `now -v` shows `12.1.2`

**Comment by ghost** [comment]
There – now it works (pun).
