### ISSUE TITLE
proxy and internal routes fighting for same port (port collisions)

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2089]
`now dev` should be smart enough to assign random ports to internal builders / routes.

Right now if you start `now dev` it starts a proxy at port 3000.
If you have `@now/node` as a builder and route, it will also try to run at port 3000 and will die

```
Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/private/var/folders/jg/y_m7qwsn13g7hq4gv07m016c0000gn/T/zeit-fun-8b44bd55e54ba/launcher.js:20:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

Current workaround is to launch `now dev` with `---port` option.

Since `now dev` receives a port at startup, one can assume it should be smart enough to assign random ports to its builders / routes to avoid such port collision in future.

**Comment by TooTallNate** [comment]
This is fixed for our builders at this point.

**Comment by stefanjudis** [comment]
Heyo, thanks for the great new `now dev` command and sorry for jumping into a closed issue. 

I just created a new project with `now init` and picked `nodejs-micro` as a template. 

After running running `now dev` I'm running exactly into the same exception. Could it's not solved for all the builders?
