### ISSUE TITLE
[now dev] Locally linked packages are replaced with uploaded/upstream versions

### ISSUE THREAD

**Issue by arunesh90** [vercel/vercel#2432]
Like the title says, locally linked packages with `yarn link`/`npm link` get replaced with the uploaded/upstream versions after initializing. This makes it hard to test out routes with local packages

**Comment by sdgandhi** [comment]
In fact, if you have an unpublished package being `npm link`ed to, it won't find the package at all.

**Comment by TooTallNate** [comment]
This seems like a bug in `yarn`. In fact, I found this issue: https://github.com/yarnpkg/yarn/issues/4770. I suggest bringing this issue up on that repo since it sounds like it's still not working as expected.

Just in case it was fixed in a newer yarn version, I've created this pull request: https://github.com/zeit/now-cli/pull/2780

Closing since there's nothing we can do in Now CLI to prevent the yarn behavior.

**Comment by sdgandhi** [comment]
@TooTallNate still an issue with `npm link`.

**Comment by arunesh90** [comment]
^ Like I said, it also happens with npm, so it's not a yarn-specific issue

**Comment by lovenick** [comment]
Can confirm the same issue (yarn and npm). When trying to use `now dev` with a locally linked package that isn't published, it errors with `Cannot find module 'xyz'`.

**Comment by geekdada** [comment]
The easiest way for now is:

1. Delete the symlink in node_modules. In your case, it's `node_modules/xyz`.
2. Create a new symlink named `xyz` in node_modules using absolute path. If you're using Yarn, it'd be `/Users/<your name>/.config/yarn/link/xyz`.
3. `now dev` should be working.

**Comment by arunesh90** [comment]
@TooTallNate can this issue be re-opened?

**Comment by elie222** [comment]
> The easiest way for now is:
> 
> 1. Delete the symlink in node_modules. In your case, it's `node_modules/xyz`.
> 2. Create a new symlink named `xyz` in node_modules using absolute path. If you're using Yarn, it'd be `/Users/<your name>/.config/yarn/link/xyz`.
> 3. `now dev` should be working.

Can confirm this works but would be good to reopen this issue. Not an easy workaround

**Comment by leofisG** [comment]
Hi I am also experiencing issue with `yarn link` when trying to deploy with Vercel, can some one let me know how to fix it? So basically I have a mono repo which contains several projects, and I want to deploy one of them which depends on an unpublished package in my mono repo. However when I do `yarn link` then `yarn link <package-name>` it's still not able to find it.

**Comment by mikestopcontinues** [comment]
Did anyone find a good solution to this? 

I'm hitting the same issue using npm, pnpm, and yarn for workspaces to share code in a monorepo.

**Comment by mikestopcontinues** [comment]
@TooTallNate @geekdada 

I suspect the issue is about more than just being absolute links. I just wrote a script to rewrite the my internal package links and still have the problem. See the before and after... Then the error...

```
19:20:13.750 | ../../../../tools/jest-preset   // <==== BEFORE
-- | --
19:20:25.663 | Rewriting @arc symlinks to be absolute.
19:20:25.675 | Symlinks written!
19:20:25.749 | /vercel/path0/tools/jest-preset  // <==== AFTER
19:20:25.751 | Detected Next.js version: 11.0.1
19:20:25.947 | Running "pnpm run deploy"
19:20:26.295 | > @arc/app-view@ deploy /vercel/path0/app/app-view
19:20:26.296 | > pnpm run test:ci && pnpm run build
19:20:26.643 | > @arc/app-view@ test:ci /vercel/path0/app/app-view
19:20:26.643 | > NODE_ENV=test jest --passWithNoTests --ci --forceExit
19:20:26.806 | ● Validation Error:
19:20:26.806 | Preset @arc/jest-preset not found.
19:20:26.806 | Configuration Documentation:
19:20:26.806 | https://jestjs.io/docs/configuration
19:20:26.811 | ERROR  Command failed with exit code 1.
19:20:26.817 | ERROR  Command failed with exit code 1.
19:20:26.831 | Error: Command "pnpm run deploy" exited with 1
```

**Comment by mikestopcontinues** [comment]
I just received a message from support. Symlinks don't work at all in the build step. None of the above solutions will fix this.

**Comment by peter-stuart-turner** [comment]
Also need a workaround for this? How are you meant to have shared code (between NextJS and React Native, for instance)
