### ISSUE TITLE
now alias without any arguments is broken

### ISSUE THREAD

**Issue by andrewlinfoot** [vercel/vercel#2941]
Hey Zeit team,

It looks like the latest update broke using `now alias` without any arguments.

This seems to be the responsible code: https://github.com/zeit/now/commit/7c421f92e144778c0074a27a212157be9901b681#diff-b79436b8a38c46520f80ad57562b4817R82-R91

We have our alias's set up in JSON config files and I believe the old functionality was such that you could call `now alias` and specify a config with `{ ... "alias": "some-alias.com" ... }` and it would read the alias name from the config and default to the latest deployment when you supplied no arguments. This doesn't appear to be working in our CI/CD anymore:

```
$ now alias --local-config=now.production.json -t TOKEN -T TEAM_NAME
> WARN! The "--team" flag is deprecated. Please use "--scope" instead.
> Error! The provided argument "undefined" is not a valid deployment
```

**Comment by codinronan** [comment]
It is also no longer reading that valid argument from the clipboard, which is functionality that has existed for a long time. I'm going to be forced to pin to an earlier version until/if this is corrected.

**Comment by TooTallNate** [comment]
Thanks for the report. This is definitely an unfortunate regression, and we will fix the previous behavior ASAP!

**Comment by andrewlinfoot** [comment]
> Thanks for the report. This is definitely an unfortunate regression, and we will fix the previous behavior ASAP!

No worries, maintaining an OSS CLI against regressions is hard 🙂 Thanks for the quick reply! Looking forward to the fix.

**Comment by cfjedimaster** [comment]
I'm using the latest (16.2.0) and still have this issue. I'm running `now alias --token XXX` and I get this error.

**Comment by cfjedimaster** [comment]
FYI, installing now@canary works. (Thank you to Leo Lamprecht.)

**Comment by IikkaWinter** [comment]
Same here, 16.2.0 still has the same issue.
