### ISSUE TITLE
API Functions sharing ressources exceeds Vercel size limit

### ISSUE THREAD

**Issue by BjoernRave** [vercel/vercel#4739]
I have one API function to generate a pdf via puppeteer. It looks like this: 
```
import chrome from 'chrome-aws-lambda'
import { NextApiRequest, NextApiResponse } from 'next'
import puppeteer from 'puppeteer'
import { parse } from 'url'

export const generatePDF = async (url: string, token: string) => {
  const browser = await puppeteer.launch(
    process.env.NODE_ENV === 'production'
      ? {
          args: chrome.args,
          executablePath: await chrome.executablePath,
          headless: chrome.headless,
        }
      : {}
  )
  const page = await browser.newPage()
  await page.setViewport({
    width: 1500,
    height: 2121,
    deviceScaleFactor: 2,
  })

  await page.setCookie({
    name: 'authorization',
    value: token,
    url,
    expires: Date.now() / 1000 + 10,
  })
  await page.goto(url, { waitUntil: 'networkidle2' })
  const pdf = await page.pdf({
    printBackground: true,
    height: 1216,
    width: 860,
  })

  await browser.close()
  return pdf
}

export default async function (req: NextApiRequest, res: NextApiResponse) {
  const parsed = parse(req.url, true)

  if (!parsed.query.url || !req.headers.authorization) {
    return res.end('Please provide required infos')
  }

  try {
    const pdf = await generatePDF(
      decodeURIComponent(parsed.query.url as string),
      req.headers.authorization.replace('Bearer ', '')
    )
    res.end(pdf)
  } catch (error) {
    res.writeHead(500, { 'Content-Type': 'text/plain' })
    res.end('There was an error performing the action')
  }
}
```
I don't import any files from a common file, but vercel is still sharing the dependencies across all API functions, exceeding the 50mb limit for my other functions

**Comment by HaNdTriX** [comment]
@BjoernRave please note that you are using `puppeteer` instead of `puppeteer-core`. `puppeteer` comes packed with chromium wich might cause your size limit issues.

more infos: https://www.npmjs.com/package/puppeteer-core#puppeteer-core

**Comment by styfle** [comment]
Indeed, the full `puppeteer` package cannot fit in a Serverless Function. The maximum size is [50MB](https://vercel.com/docs/v2/platform/limits#serverless-function-size).


- puppeteer: [![install size](https://packagephobia.com/badge?p=puppeteer@5.3.1)](https://packagephobia.com/result?p=puppeteer@5.3.1)

- puppeteer-core: [![install size](https://packagephobia.com/badge?p=puppeteer-core@5.3.1)](https://packagephobia.com/result?p=puppeteer-core@5.3.1)

Consider using `puppeteer-core` instead.

**Comment by BjoernRave** [comment]
@styfle The problem is not puppeteer, but headless chrome. That is why I am using `chrome-aws-lambda`. I can deploy the above code as an API function as standalone, it doesnt exceed the 50mb limit. The problem is when putting this lambda function in the `/api` folder inside `next.js` it exceeds the size, because the dependencies are shared between api functions, although they don't use any shared code

**Comment by styfle** [comment]
I see, this sound similar to Issue #4013 which was fixed in PR #4018.

Can you share a repo using `puppeteer-core` that is exceeding the 50MB size?

**Comment by BjoernRave** [comment]
@styfle sorry, for taking so long. I created a reproduction of the problem here: https://github.com/BjoernRave/vercel-api-size-repro. You can just deploy it with `vercel` and see the problem.

It is basically this example: https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-nextjs

with an invoicing api function added

**Comment by BjoernRave** [comment]
@styfle should I open a new issue with this or will you re-open this one?

**Comment by ChrisLusted** [comment]
@BjoernRave did you have any luck getting this deployed? experiencing a similar issue, very frustrating

**Comment by BjoernRave** [comment]
@ChrisLusted no, currently the only option is to move the `/api` folder in the root. The problem is that the deployment time increases dramatically, because it builds the whole thing for every api function

**Comment by ChrisLusted** [comment]
@BjoernRave thanks for the quick reply 👍  

do you mean move the whole `/api` folder to the root of the app and outside of pages directory?

**Comment by BjoernRave** [comment]
yes, vercel picks up serverless functions defined in `/api` in the root: https://vercel.com/docs/serverless-functions/introduction

**Comment by leandrorazevedo** [comment]
@BjoernRave did you have any solution of this issue ?

**Comment by transitive-bullshit** [comment]
I tried everything to get `chrome-aws-lambda` working, and @BjoernRave's advice is the only thing that worked.

So weird that moving the serverless function from `pages/api/` to `api/` solved the lambda size issue.

This definitely seems like a bug with next / vercel.

**Comment by BjoernRave** [comment]
yes, it is a bug with vercel, where the api routes are not properly split, but seems like no one is noticing my reproduction here, will create a new issue.

**Comment by mdugue** [comment]
any news on this?

**Comment by BjoernRave** [comment]
@mdugue I talked to the support about this and they said the behavior is expected. Doesn't seem right to me, but what can you do

**Comment by transitive-bullshit** [comment]
@styfle this is a bug with either next.js or vercel.

The same serverless function under `pages/api/example.js` fails with a limit exceeded whereas `api/example.js` succeeds.

One related minor annoyance is that running `next dev` doesn't actually pick up serverless functions at the top-level `api/`, but it does pick up serverless functions under `pages/api/`. So I have to tell my users to run `vercel dev` instead for local development.

There are probably multiple subtle bugs here, and some are with next.js and some are with vercel, but this should definitely be investigated by the vercel team at whatever priority they deem appropriate.

**Comment by mdugue** [comment]
@styfle @transitive-bullshit thanks for your replies. If intended this is definitely weird behavior. 

Actually I was able to reproduce the same problem by changing an api route to a `[...dynamic]` one without further code changes. It’s somewhat a pitty as it limits using vercel for generating PDFs quite a bit

**Comment by Xaconi** [comment]
Another case here. Using `puppeteer-core` and `chrome-aws-lambda` gave me the "Limit exceeded error" but changing the API folder from `/pages/api/` to `/api/` solved my case. It's a NextJS/Vercel bug.

**Comment by JavierMartinz** [comment]
I'm using NextJS & Vercel together with `puppeteer-core` and `chrome-aws-lambda` which  are giving me the "Limit exceeded error. How did you change the folder to solve it @Xaconi @transitive-bullshit ?

I mean, I managed to move my function from `src/pages/api/example.js` to `src/api/example.js` and build are not failing anymore. However, https//my-example.vercel.app/api/example is not working anymore.

**Comment by pepsiamir** [comment]
same problem here

`
<html><body>


22:06:18.910 | Serverless Function's page: api/generate.js
-- | --
22:06:18.912 | Large Dependencies                  Uncompressed size  Compressed size
22:06:18.912 | node_modules/chrome-aws-lambda/bin            49.6 MB          49.5 MB
22:06:18.912 | node_modules/encoding/node_modules             329 kB           179 kB
22:06:18.912 | node_modules/puppeteer-core/lib                527 kB           136 kB
22:06:18.912 | All dependencies                              51.8 MB          50.2 MB
22:06:18.912 | Max serverless function size was exceeded for 1 function
22:06:19.029 | Created all serverless functions in: 3.229s
22:06:19.915 | Uploading build outputs...
22:06:20.651 | Deploying build outputs...
22:06:29.700 | Build completed. Populating build cache...
22:06:35.431 | Uploading build cache [81.42 MB]...
22:06:38.297 | Build cache uploaded: 2.865s
22:06:38.817 | Done with "package.json"


</body>
</html>`

**Comment by v3dillon** [comment]
+1

**Comment by joffreyBerrier** [comment]
> I'm using NextJS & Vercel together with `puppeteer-core` and `chrome-aws-lambda` which are giving me the "Limit exceeded error. How did you change the folder to solve it @Xaconi @transitive-bullshit ?
> 
> I mean, I managed to move my function from `src/pages/api/example.js` to `src/api/example.js` and build are not failing anymore. However, https//my-example.vercel.app/api/example is not working anymore.

I have the same issue, How did you get it to work then?

**Comment by Xaconi** [comment]
@joffreyBerrier I have a production example working on my blog (repo here ==> https://github.com/Xaconi/xaconi-site). I have the function on `/api/social-image` and in order to call that function, I need to make a GET query to https://xaconi.dev/api/social-image/post_url_rewrite.jpg (for example, https://xaconi.dev/api/social-image/como-crear-sliders-con-css-scroll-snap.jpg). I hope this helps.

**Comment by DylanVann** [comment]
`chrome-aws-lambda` has been edging up in size, probably due to Chrome doing so as well, leaving less size for any other code.

```
v10 - 49.7 MB
v9  - 49.0 MB
v8  - 48.9 MB
v7  - 48.8 MB
```

I downgraded `chrome-aws-lambda` and `puppeteer-core` to `v8`, haven't noticed any functionality I needed missing, and it fits within the lambda limit.

**Comment by viveknigam3003** [comment]
> `chrome-aws-lambda` has been edging up in size, probably due to Chrome doing so as well, leaving less size for any other code.
> 
> ```
> v10 - 49.7 MB
> v9  - 49.0 MB
> v8  - 48.9 MB
> v7  - 48.8 MB
> ```
> 
> I downgraded `chrome-aws-lambda` and `puppeteer-core` to `v8`, haven't noticed any functionality I needed missing, and it fits within the lambda limit.

Exactly! I was facing the same problem, and thought maybe going from v9 to v10 would solve the issue, but instead, it made it worse.
Also this limit exceeding issue started when I shifted from Next 10 to Next 11 :/

**Comment by akameoww** [comment]
> > I'm using NextJS & Vercel together with `puppeteer-core` and `chrome-aws-lambda` which are giving me the "Limit exceeded error. How did you change the folder to solve it @Xaconi @transitive-bullshit ?
> > I mean, I managed to move my function from `src/pages/api/example.js` to `src/api/example.js` and build are not failing anymore. However, https//my-example.vercel.app/api/example is not working anymore.
> 
> I have the same issue, How did you get it to work then?

+1

**Comment by olivertilk** [comment]
I am using `puppeteer-core` and `chrome-aws-lambda` and I had this same issue with Vercel. I was able to stay under the 50MB limit by moving my endpoint from a Next.js serverless function at `/pages/api/example.js` to a Node.js serverless function at `/api/example.js` in the Next.js folder structure, even when using the latest version of `chrome-aws-lambda`.

Following the instructions at https://vercel.com/docs/concepts/functions/introduction, I had to change
```
import nextConnect from 'next-connect';

const handler = nextConnect();
handler.get( async (req, res) => { } );

export default handler;
```
to
```
module.exports = async (req, res) => { }
```

Once deployed to Vercel, I am able to call the same path as before: example.com/api/example

A downside of this approach is that the build step is performed twice, once for the Next.js serverless functions and once for the Node.js serverless functions.

**Comment by steveruizok** [comment]
Still an issue. Thanks for the help all.

**Comment by Emibob** [comment]
+1 Still an issue

**Comment by jagadyudha** [comment]
+1 Still an issue

**Comment by theDigg** [comment]
+1 Still an issue

**Comment by jagadyudha** [comment]
> +1 Still an issue

Vercel log helped me solve this problem. 

My issue is that I'm overusing react-icons. Everything was fixed after eliminating a few react-icons 😀

![image](https://user-images.githubusercontent.com/41937681/155841294-ed3a0e96-bc82-4f17-a6c2-66fb52340a57.png)

**Comment by BrunoQuaresma** [comment]
+1 Still an issue

**Comment by Julianwan** [comment]
Glad I found this thread... still an issue here

**Comment by hananiradzi** [comment]
It's still happening, quite frustrated. Is there any way to avoid this issue?. I'm pretty sure chrome's size will increase in future.

**Comment by Julianwan** [comment]
Just to echo what @viveknigam3003 said, having these two versions in my `package.json` gave me no issue:

```
"puppeteer-core": "^8.0.0",
"chrome-aws-lambda": "^8.0.2",
```

**Comment by mikebuilds** [comment]
+1 still an issue. 

Per the comments from @jagadyudha, it looks like Next JS API routes bundles in additional information??? which pushes it over the 50mb limit. I still had size issues even after downgrading to version 8 of puppeteer-core and chrome-aws lambda.

What did solve it is moving the files to **/api**/route.ts instead of **/pages/api**/route.ts

The difference is so stark that I was even able to use the latest versions of puppeteer, with it's webp support.

On a side note, for anyone who get's past this, and then runs into a *cannot find module* issue. Vercel now opts new project to Node 16.  chrome-aws-lambda max support is 14. You can downgrade to use Node 14 in the vercel settings. There is a pull request to update the library here: https://github.com/alixaxel/chrome-aws-lambda/pull/274

**Comment by leerob** [comment]
Hey! If anyone is still trying to use Chromium/Puppeteer for taking screenshots inside Serverless Functions, could you send me an email `lee@vercel.com` with more information about what you're trying to build? Thank you!

**Comment by PedroHenrique-F** [comment]
Fancing the same problem, someone has found a workaround about this?

**Comment by yareyaredesuyo** [comment]
Easiest way to solve this problem is just downgrade chrome-aws-lambda, no need to use latest version.

And use node 14.x version.

**Comment by PedroHenrique-F** [comment]
> Easiest way to solve this problem is just downgrade chrome-aws-lambda, no need to use latest version.

even tho i'm still facing the same problem... :/

**Comment by Xaconi** [comment]
I manage to solve the problem with this change => https://github.com/vercel/vercel/issues/4739#issuecomment-803428521

**Comment by PedroHenrique-F** [comment]
> I manage to solve the problem with this change => [#4739 (comment)](https://github.com/vercel/vercel/issues/4739#issuecomment-803428521)

and are u still able to access the api route url? eg: ${baseUrl}/api/route.ts ?

**Comment by leerob** [comment]
Good news! We have a new solution for dynamic social card images: https://vercel.com/blog/introducing-vercel-og-image-generation-fast-dynamic-social-card-images

**Comment by Ajmaljalal** [comment]
this is still an issue, don't why this is closed without a proper solution.

**Comment by leerob** [comment]
@Ajmaljalal you can continue the discussion here -> https://github.com/orgs/vercel/discussions/103
