### ISSUE TITLE
Yarn global downloads now every time

### ISSUE THREAD

**Issue by albinekb** [vercel/vercel#602]
![image](https://cloud.githubusercontent.com/assets/5027156/26564108/fbc22f08-44dc-11e7-9cd8-85da1312f92f.png)

Whenever i install something globally, `now` seems to download itself again? and build?

output when done
```
❯ yarn global add fkill-cli
yarn global v0.24.6
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠂ now: > For the sources, check out: https://github.com/zeit/now-cli
success Installed "fkill-cli@3.6.0" with binaries:
      - fkill
warning No license field
✨  Done in 34.88s.
```

I guess it's because the `📃  Building fresh packages` step, but I think this should be fixed, since it makes global install a lot slower

**Comment by chabou** [comment]
`now` is redownloaded with a `yarn global ls`. Maybe it is a `yarn` bug ?
![capture d ecran 2017-05-30 a 08 08 42](https://cloud.githubusercontent.com/assets/4137761/26570186/6e9c22ae-450f-11e7-8414-85461656eac2.png)

**Comment by albinekb** [comment]
Here's the problem: https://github.com/iarna/in-publish/issues/9 

But I don't understand this download thing that's going on, why not just publish the package and let npm/yarn handle the download 😱

**Comment by leo** [comment]
@albinekb We need a separate binary per platform, otherwise we would simply include it in the package, of course! 😊 We can't ship all binaries, then the package would be too huge.

**Comment by albinekb** [comment]
But why ship the binary in `npm` when you install with `npm` (or `yarn`) it's 100% that you have node installed too, then you download *another* copy of node? 🤔 

The binary is great for `brew` etc but it feels weird to download all source files *and* a compiled binary with *another* version of node when installing with **n**(ode) **package manager** ?

**Comment by leo** [comment]
@albinekb We've talked several weeks about this internally and it was a hard decision - but [here](https://github.com/zeit/now-cli#why-ship-a-pkg-ed-binary) are the reasons (+ we can control the node version).

**Comment by albinekb** [comment]
>We're able to select our own Node version of choice and can take advantage of the latest features

This makes it totally worth it 😂  (gonna start ship node 8 with all my CLIs :trollface:)

>Increased safety by providing a unified signature mechanism for releases

There are no signature checks (if i'm not missing them) https://github.com/zeit/now-cli/blob/master/download/src/index.js

but ok. the consistency part is 👍 

~I'll have a PR up tomorrow with a fix for yarn and prepublish, tired of waiting for the now download every time I do something global :spinner:~

**Comment by jesstelford** [comment]
Running into this today to the point where the now binary download hangs, meaning I can't `yarn global add` anything :'(

_Edit_: After reading the link from @leo, I can't say I agree with any of those points except the first one:

> Simpler installation for non-Node users like those deploying static files or Dockerfiles.

In all other cases, it's more of a hassle, and more of a network drain to re-download a huge binary (even if you already have it installed) every time you install _another package_.

For the non-Node use-case; provide a binary, that's a great idea. But for the node-use case, it should be shipping the code. Use babel if you have to, or put a minimum node version required in the `package.json`'s `"engine"` field.

**Comment by leo** [comment]
We've been through all of that for more than a year now (since the first CLI release) and it never worked out for us. In turn, we decided to go this road. When thinking about this, Now Desktop (which also installs the bundled CLI and can never install a npm package) also needs to be considered. This - as it is - is simply the best solution to cover all cases.

Let's take a look at how to fix this yarn issue! npm is already handling it properly.

**Comment by mattfysh** [comment]
Also getting severely hampered by this issue, may try and use just npm for now-cli and yarn for everything else... unless anyone knows of another workaround for yarn?

**Comment by matheuss** [comment]
@leo @igorklopov any update on this? `yarn global add sth` takes a long time every time 😩

**Comment by wong2** [comment]
I'm facing this problem too. What's worse, the request hang up with ECONNRESET, which makes the install failing.

**Comment by mattfysh** [comment]
I believe this is fixed in the latest release of now? Just switch from an npm global to yarn global install, and all is well

**Comment by albinekb** [comment]
Yep seems to be fixed!

**Comment by albinekb** [comment]
This is back again:
```
reforce@reforces-MacBook-Pro ~/D/frontend-construction> yarn global remove scandium
yarn global v1.3.2
[1/2] Removing module scandium...
[2/2] Regenerating lockfile and installing missing dependencies...
[1/1] ⢀ now: > For the source code, check out: https://github.com/zeit/now-cli
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...

```

Why does it download `now` when I'm removing another completely unrelated package? This is nuts.

**Comment by jesstelford** [comment]
Ooof, ran into this again today - trying to do a `yarn global add gatsby-cli`, just hangs while `now` spins. A quick `yarn global remove now` makes all the issues go away.

Using `npm install -g now` works fine.

Really wish there was a solution for this that didn't involve breaking yarn :(

_Edit:_ Nope, still broken. Turns out `yarn global remove now` didn't actually remove `now`.

Instead, it left `/Users/jess/.config/yarn/global/node_modules/.bin/now` binary (which links to `/Users/jess/.config/yarn/global/node_modules/now/download/dist/now`). But that binary contains the following:

```javascript
#!/usr/bin/env node
console.log("The 'now' installation did not complete successfully.")
console.log("Please run 'npm i -g now' to reinstall!")
```

Not sure if that comes from `npm` or `yarn`, but either way it's busted 100%.

_Edit 2:_ Doing a `rm -rf /Users/jess/.config/yarn/global/node_modules/now` fixed it, so it's using the `npm` version.

What a rollercoaster!

**Comment by jamonholmgren** [comment]
I believe this issue is directly related to this Yarn issue: https://github.com/yarnpkg/yarn/issues/5680

**Comment by Akryum** [comment]
Still happening, and if you don't have fiber, you're basically screwed up...

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!
